# Generated by Django 2.2.6 on 2019-11-01 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('teamcity_resource', models.URLField(blank=True, unique=True)),
                ('name', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_reserved', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.CharField(blank=True, max_length=30, null=True)),
                ('reserved_for', models.CharField(blank=True, choices=[('Teamcity', 'Teamcity'), (None, 'Not reserved')], default=None, max_length=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Pool')),
            ],
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='DNS host name or IP address where USB device can be found', max_length=200)),
                ('bus_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Resource')),
            ],
            options={
                'unique_together': {('host', 'bus_id')},
            },
        ),
    ]
