# Generated by Django 2.2.6 on 2019-11-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='teamcity_resource',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
