# Generated by Django 3.0.3 on 2020-03-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191222_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('communicator', models.CharField(choices=[('SSH', 'SSH')], max_length=50)),
                ('config_json', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.RemoteHost'),
        ),
    ]
