# Generated by Django 2.2.7 on 2019-11-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191101_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='teamcity_resource',
        ),
    ]
