# Generated by Django 2.2.7 on 2019-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_pool_teamcity_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='reserved_for',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
