# Generated by Django 2.2.7 on 2019-11-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191108_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='config_json',
            field=models.TextField(default='UsbipOverSSH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='driver',
            field=models.CharField(default='UsbipOverSSH', max_length=100),
            preserve_default=False,
        ),
    ]
