# Generated by Django 3.0.3 on 2020-03-10 18:24
import json

from django.db import migrations

from data.models import Device, RemoteHost


def initialize_hosts(apps, schema_editor):
    for device in Device.objects.all():
        device_config = json.loads(device.config_json)
        if 'host' in device_config:
            host = device_config['host']
        elif 'hub_address' in device_config:
            host = device_config['hub_address']
        else:
            break
        if not RemoteHost.objects.filter(address=host, communicator="SSH").exists():
            new_host = RemoteHost(address=host, communicator="SSH")
            new_host.save()


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0004_device_id'),
    ]

    operations = [
        migrations.RunPython(initialize_hosts)
    ]
