# Generated by Django 3.0.3 on 2020-03-11 23:26

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('data', '0005_auto_20200311_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        )
    ]
