# Generated by Django 3.0.3 on 2020-03-11 23:11

from django.db import migrations, models
import django.db.models.deletion

from data.models import Device


def remove_host_from_json(apps, schema_editor):
    for device in Device.everything.all():
        config = device.config
        if 'host' in config:
            del config['host']
            device.set_config(config)
            device.save()
        elif 'hub_address' in config:
            del config['hub_address']
            device.set_config(config)
            device.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200310_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.RemoteHost'),
        ),
        migrations.RunPython(remove_host_from_json)
    ]
