# Generated by Django 2.2.7 on 2019-11-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20191118_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='use_password',
            field=models.CharField(blank=True, help_text='Random password needed to request access to devices in this group', max_length=30, null=True),
        ),
    ]
