# Generated by Django 2.2.7 on 2019-11-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_resource_use_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='device',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='host',
        ),
    ]
