# Generated by Django 3.0.3 on 2020-03-11 23:40

from django.db import migrations

from data.models import Device


def add_device_ids(apps, schema_editor):
    for index, device in enumerate(Device.everything.all(), start=0):
        device.id = index
        print(f"Setting id of {device} to {index}")
        device.save(force_update=True)


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0006_auto_20200311_1911'),
    ]

    operations = [
        migrations.RunPython(add_device_ids)
    ]
