# Generated by Django 3.0.3 on 2020-03-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_set_device_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(),
        ),
    ]
