# Generated by Django 3.0.3 on 2020-03-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200311_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.SlugField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'resource')},
        ),
    ]
