# Generated by Django 3.0.4 on 2020-04-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200311_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotehost',
            name='type',
            field=models.CharField(choices=[('Darwin', 'Darwin'), ('Linux_AMD64', 'Linux_AMD64'), ('Windows', 'Windows')], default='Linux_AMD64', max_length=20),
            preserve_default=False,
        ),
    ]
