# Generated by Django 2.2.7 on 2019-11-30 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0009_auto_20191126_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='used_by',
            new_name='used_for',
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Pool'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reserved_for',
            field=models.CharField(blank=True, choices=[('', 'NO RESERVATION'), ('ci_teamcity', 'ci_teamcity')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='use_password',
            field=models.CharField(blank=True, help_text='Random password needed to request access to devices in this resource', max_length=30, null=True),
        ),
    ]
