# Generated by Django 2.2.7 on 2019-12-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20191130_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='reserved_for',
            field=models.CharField(blank=True, choices=[('', 'NO RESERVATION'), ('ci_teamcity', 'ci_teamcity')], default='', max_length=20, null=True),
        ),
    ]
