# Generated by Django 2.2.7 on 2019-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20191202_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='driver',
            field=models.CharField(choices=[('VirtualHere', 'VirtualHere'), ('UsbipOverSSH', 'UsbipOverSSH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reserved_for',
            field=models.CharField(blank=True, choices=[('', 'NO RESERVATION'), ('ci_teamcity', 'ci_teamcity')], default='', max_length=20),
        ),
    ]
