# Generated by Django 2.2.7 on 2019-12-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20191204_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='reserved_for',
        ),
        migrations.AddField(
            model_name='device',
            name='healthy',
            field=models.BooleanField(default=True),
        ),
    ]
