# Generated by Django 2.2.7 on 2019-12-11 17:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20191210_1541'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='device',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='healthy',
            new_name='online',
        ),
    ]
