FROM python:3.8

RUN pip install pipenv
# TODO:  Multi stage so we can leave dev tools out of final image
# based on suggestions from here. https://www.python-ldap.org/en/latest/installing.html
RUN apt update && apt install -y python3.7-dev libldap2-dev libsasl2-dev

COPY Pipfile.lock Pipfile local_requirements.txt /
RUN pipenv install --system
RUN pip install -r /local_requirements.txt

WORKDIR /quartermaster
COPY quartermaster_server /quartermaster
COPY deploy/gunicorn_config.py /
CMD [ "gunicorn", "--conf", "/gunicorn_config.py", "quartermaster.wsgi"]
