# Generated by Django 3.0.1 on 2019-12-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_auto_20191222_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCityPool',
            fields=[
                ('shared_resource_url', models.URLField(blank=True, help_text='Autogenerated form name, change will be lost', null=True, unique=True)),
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('pool', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Pool')),
            ],
        ),
    ]
