# Generated by Django 3.0.3 on 2020-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamcity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcitypool',
            name='name',
            field=models.SlugField(choices=[('QUARTERMASTER_KONA', 'QUARTERMASTER_KONA'), ('QUARTERMASTER_STANDALONE_PANDA', 'QUARTERMASTER_STANDALONE_PANDA'), ('QUARTERMASTER_TOPAZ_FPGAS', 'QUARTERMASTER_TOPAZ_FPGAS')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamcitypool',
            name='shared_resource_url',
            field=models.URLField(blank=True, help_text='Autogenerated from name, will be lost', null=True, unique=True),
        ),
    ]
