# Generated by Django 2.2.7 on 2019-11-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0003_remove_pool_teamcity_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCityPool',
            fields=[
                ('shared_resource_url', models.URLField(blank=True, null=True, unique=True)),
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('pool', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Pool')),
            ],
        ),
    ]
