# Generated by Django 2.2.7 on 2019-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_teamcity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcitypool',
            name='shared_resource_url',
            field=models.URLField(blank=True, help_text='Autogenerated form name, change will be lost', null=True, unique=True),
        ),
    ]
